### PR TITLE
fix: re-export DOMRenderProps and related types to fix downstream TS2742

### PR DESCRIPTION
**Pull request by lixiaoyan**
## Summary

Re-exports the `RenderProps`-related types from `react-aria-components` so downstream packages that emit their own `.d.ts` (composite TS projects, library `dts` builds, Storybook setups with declaration emit, etc.) can name the types reachable through `RenderProps`.

The v1.17.0 types refactor split the bundled `dist/types.d.ts` into per-source files. `RenderProps` extends `StyleRenderProps` extends `DOMRenderProps`, and `StyleRenderProps['style']` uses `StyleOrFunction` — none of those names were publicly nameable from the package root. Downstream code that infers a type whose expansion crosses these names now fails with `TS2742`. Same family as #9775 (which was a `TS4023` for `TreeEmptyStateRenderProps`).

### Changes

- `packages/react-aria-components/src/utils.tsx` — add `export` to `StyleOrFunction` (the only one of the six missing the keyword in source).
- `packages/react-aria-components/exports/index.ts` — extend the type-only re-export from `../src/utils` with `DOMRenderProps`, `PossibleLinkDOMRenderProps`, `DOMRenderFunction`, `ClassNameOrFunction`, `StyleOrFunction`, `ChildrenOrFunction`.

Type-only, additive — no runtime impact, no breaking change.

## ✅ Pull Request Checklist:

- [x] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues). _Same family as #9775._
- [x] Added/updated unit tests and storybook for this change. _N/A — type-only re-export, no runtime behavior to test._
- [x] Filled out test instructions.
- [x] Updated documentation (if it already exists for this component). _N/A — internal type plumbing._
- [x] Looked at the Accessibility Practices for this feature. _N/A_

### Reproduction (before the fix)

In any downstream package that (a) wraps a RAC render-props type and (b) emits its own `.d.ts`:

```tsx
// my-component.tsx
import {forwardRef} from 'react';
import type {RenderProps} from 'react-aria-components';

interface MyRenderValues {
  isPressed: boolean;
  isHovered: boolean;
}

// Wraps RAC's RenderProps — the typical pattern when building a component
// library on top of react-aria-components.
interface MyComponentProps extends RenderProps<MyRenderValues> {
  isDisabled?: boolean;
}

export const MyComponent = forwardRef<HTMLDivElement, MyComponentProps>(
  function MyComponent(_props, _ref) {
    return null;
  }
);
```

```tsx
// my-component.stories.tsx
import type {Meta} from '@storybook/react';
import {MyComponent} from './my-component';

// `satisfies Meta<typeof MyComponent>` forces TS to materialize the
// inferred type of `default`, expanding through MyComponentProps →
// RenderProps → StyleRenderProps → DOMRenderProps, and through
// StyleRenderProps['style']: StyleOrFunction.
export default {
  title: 'MyComponent',
  component: MyComponent,
} satisfies Meta<typeof MyComponent>;
```

`tsc` (or any declaration emit) fails:

```
error TS2742: The inferred type of 'default' cannot be named without a
reference to '.../react-aria-components/dist/types/src/utils'. This is
likely not portable. A type annotation is necessary.
```

### After

Type-checks and emits cleanly. The previously-unnameable names (`DOMRenderProps`, `StyleOrFunction`, etc.) are reachable via the package root, so TS can write portable declarations.

### Why it worked in 1.16.0

The entire types surface lived in a single bundled `dist/types.d.ts` — every transitive name was reachable through that one file. The 1.17.0 per-file split made the missing public re-exports observable.

## 🧢 Your Project:

_personal_

### CODE REVIEW

**Review by reidbarber — APPROVED** [review]

**Comment by lixiaoyan** [comment]
@snowystinger Hi, any change to get this merged?

**Review by devongovett — APPROVED** [review]

**Review by snowystinger — APPROVED** [review]
