### ISSUE TITLE
[React Aria Components] Table without a TableBody throws an error

### ISSUE THREAD

**Issue by ebrpol** [adobe/react-spectrum#7350]
### Provide a general summary of the issue here

After updating from React Aria Components 1.2.1 to 1.4.1, the `Table` component throws an error when it does not contain a `TableBody` as a child.

### 🤔 Expected Behavior?

Not to throw an the error

### 😯 Current Behavior

The following error is thrown:
```
TypeError: node.render is not a function 
```

### 🖥️ Steps to Reproduce

Use the React Aria Components `Table` component without using a `TableBody` as a child

### Version

1.4.1

### What browsers are you seeing the problem on?

Other

### If other, please specify.

While running unit tests using Vitest

### What operating system are you using?

Ubuntu

**Comment by reidbarber** [comment]
TableBody is a required part of the Table. Is there a use case where you wouldn't use it?

**Comment by ebrpol** [comment]
Beyond that, the error that is thrown is quite cryptic. Even if you don't want to "fix" this issue, I think it would help if the error description were a bit more helpful.

**Comment by reidbarber** [comment]
> We are using a Table with just a TableHead as a footer for a Table above it. The footer is glued to the bottom of the page, so even if there are not many rows in the table, the footer is at the bottom.

I see. You can probably just render some non-RAC elements instead in the meantime.

> I think it would help if the error description were a bit more helpful.

While that would be better DX, strictly enforcing component structure at runtime would be costly in maintenance and bundle size, so I'm not sure we want to do that. Since all the examples in the docs include a TableBody, I think it should be well-understood that it is required. It could be part of https://github.com/adobe/react-spectrum/issues/2944, if we are ever able to implement that though.
